#pragma once

#include "CoreMinimal.h"

/**
* Version info.
*
* !!!! DO NOT EDIT THIS FILE BY HAND !!!!
* !!!! ANY FILE CHANGES WILL BE LOST !!!!
* !!!!    DO NOT COMMIT THIS FILE    !!!!
*/
namespace FVersionInfo
{
    static const FString BranchName = "%BRANCH_NAME%";
    static const FString CommitShort = "%COMMIT_SHORT%";
    static const FString CommitLong = "%COMMIT_LONG%";
    static const FString BuildTimeUTC = "%BUILD_TIMEUTC%";
    static const FString BuildTimeLocal = "%BUILD_TIMELOCAL%";
}
